import streamlit as st
import requests
from fpdf import FPDF
from datetime import datetime
import re

st.set_page_config(page_title="CuraBot | AI Medical Research", page_icon="⚕️", layout="wide")

# Dashboard Styling
st.markdown("""
    <style>
    .main { background-color: #0e1117; }
    .medical-title { font-size: 3rem; font-weight: 800; color: #ffffff; margin-bottom: 0px; display: inline-block; }
    .medical-subtitle { color: #ffffff; font-size: 1.4rem; font-weight: 600; font-style: italic; margin-top: 10px; margin-bottom: 25px; }
    .stTextArea label { color: #ffffff; font-weight: 500; font-size: 1.1rem; margin-bottom: 8px; }
    .stTextArea textarea { background-color: #1e2129; color: white; border: 1px solid #3e424b; border-radius: 10px; }
    .result-card { background-color: #161b22; padding: 30px; border-radius: 15px; border: 1px solid #30363d; margin-top: 25px; }
    .stButton>button { background-color: #ff4b4b; color: white; border-radius: 8px; border: none; font-weight: bold; width: 100%; height: 3.5em; transition: 0.3s; }
    section[data-testid="stSidebar"] { background-color: #161b22; border-right: 1px solid #30363d; }
    </style>
    """, unsafe_allow_html=True)

def sanitize_text(text):
    # Remove markdown symbols and common AI artifacts like "bullet --"
    clean = re.sub(r'[*_#]', '', text)
    clean = clean.replace('bullet --', '').replace('bullet', '').strip()
    return clean.encode('latin-1', 'ignore').decode('latin-1')

def generate_pdf(report_text):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    
    # --- PROFESSIONAL HEADER ---
    pdf.set_fill_color(41, 128, 185) 
    pdf.rect(0, 0, 210, 45, 'F')
    
    pdf.set_y(12)
    pdf.set_font("helvetica", 'B', 24)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, "CURABOT", align='C', ln=True)
    
    pdf.set_font("helvetica", 'B', 14)
    pdf.cell(0, 10, "CLINICAL RESEARCH SUMMARY", align='C', ln=True)
    
    pdf.set_font("helvetica", 'I', 9)
    pdf.cell(0, 8, f"Document ID: CB-{datetime.now().strftime('%Y%m%d%H%M')}  |  Generated: {datetime.now().strftime('%B %d, %Y')}", align='C', ln=True)
    
    # --- BODY START ---
    pdf.set_y(55)
    pdf.set_text_color(44, 62, 80)
    
    sections = report_text.split('\n')
    for line in sections:
        line = line.strip()
        if not line or line.startswith('---'):
            continue
            
        # Section Header Logic
        upper_line = line.upper()
        if "REPORTED SYMPTOMS" in upper_line:
            pdf.ln(5)
            pdf.set_font("helvetica", 'B', 12)
            pdf.set_text_color(22, 160, 133)
            pdf.cell(0, 10, "REPORTED SYMPTOMS", ln=True)
            pdf.set_draw_color(22, 160, 133)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
        elif "RESEARCH FINDINGS" in upper_line:
            pdf.ln(5)
            pdf.set_font("helvetica", 'B', 12)
            pdf.set_text_color(41, 128, 185)
            pdf.cell(0, 10, "KEY CLINICAL RESEARCH FINDINGS", ln=True)
            pdf.set_draw_color(41, 128, 185)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
        elif "CLINICAL CONSIDERATIONS" in upper_line:
            pdf.ln(5)
            pdf.set_font("helvetica", 'B', 12)
            pdf.set_text_color(211, 84, 0)
            pdf.cell(0, 10, "CLINICAL CONSIDERATIONS", ln=True)
            pdf.set_draw_color(211, 84, 0)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
        elif "NEXT STEPS" in upper_line:
            pdf.ln(5)
            pdf.set_font("helvetica", 'B', 12)
            pdf.set_text_color(44, 62, 80)
            pdf.cell(0, 10, "RECOMMENDED NEXT STEPS", ln=True)
            pdf.ln(1)
        
        # Paragraph & Bullet Logic
        else:
            pdf.set_text_color(60, 60, 60)
            pdf.set_font("helvetica", '', 10)
            if line.startswith(('*', '-', 'bullet')):
                clean_line = sanitize_text(line)
                if clean_line:
                    pdf.set_x(15)
                    pdf.write(6, chr(149) + " ") 
                    pdf.multi_cell(0, 6, clean_line)
                    pdf.ln(1)
            else:
                clean_line = sanitize_text(line)
                if clean_line:
                    pdf.multi_cell(0, 6, clean_line)
                    pdf.ln(1)

    # --- DISCLAIMER FOOTER ---
    # Set y to bottom - 40 to ensure it doesn't overlap content
    if pdf.get_y() > 250:
        pdf.add_page()
        
    pdf.set_y(-40)
    pdf.set_fill_color(253, 237, 236)
    pdf.set_draw_color(231, 76, 60)
    pdf.set_text_color(192, 57, 43)
    pdf.set_font("helvetica", 'B', 8)
    pdf.cell(0, 6, "IMPORTANT MEDICAL DISCLAIMER", align='C', ln=True, border='LTR', fill=True)
    pdf.set_font("helvetica", 'I', 8)
    disclaimer = ("This report is generated by CuraBot (AI Research Assistant) for informational purposes only. "
                  "It is NOT a medical diagnosis or professional advice. Information is synthesized from PubMed "
                  "and may not reflect current clinical guidelines. Always consult a licensed physician.")
    pdf.multi_cell(0, 5, disclaimer, border='LBR', align='C', fill=True)
    
    return bytes(pdf.output())

# Sidebar
with st.sidebar:
    st.markdown("### 🔍 About CuraBot")
    st.info("CuraBot leverages AI agents to analyze symptoms and cross-reference clinical research from PubMed.")
    st.markdown("---")
    st.markdown("### ⚠️ Emergency Info")
    st.error("Seek immediate medical help for severe symptoms like chest pain or difficulty breathing.")

# Header
st.markdown("<h1 class='medical-title'>⚕️ CuraBot</h1>", unsafe_allow_html=True)
st.markdown("<p class='medical-subtitle'>Your Intelligent Health Research Partner</p>", unsafe_allow_html=True)

user_input = st.text_area("What symptoms are you experiencing?", 
                          placeholder="e.g., persistent cough and mild fever for 3 days", 
                          height=150)

col1, col2, col3 = st.columns([1,1,1])
with col2:
    search_btn = st.button("Generate Medical Analysis")

if search_btn:
    if user_input:
        with st.status("🩺 Running Clinical Agents...", expanded=True) as status:
            try:
                response = requests.get("http://127.0.0.1:8000/analyze", params={"symptoms": user_input}, timeout=180)
                if response.status_code == 200:
                    st.session_state.report_content = response.json().get("analysis")
                    status.update(label="Analysis Complete!", state="complete", expanded=False)
                else:
                    st.error(f"Backend Error: {response.status_code}")
            except Exception as e:
                st.error(f"Connection Error: Ensure backend is running. ({e})")
    else:
        st.warning("Please enter symptoms before analyzing.")

if 'report_content' in st.session_state and st.session_state.report_content:
    st.markdown("---")
    st.markdown("### 📋 Clinical Research Summary")
    st.markdown('<div class="result-card">', unsafe_allow_html=True)
    st.markdown(st.session_state.report_content)
    st.markdown('</div>', unsafe_allow_html=True)
    
    pdf_bytes = generate_pdf(st.session_state.report_content)
    st.download_button(
        label="📥 Download Professional Clinical Report",
        data=pdf_bytes,
        file_name=f"CuraBot_Research_{datetime.now().strftime('%Y%m%d')}.pdf",
        mime="application/pdf",
        use_container_width=True
    )
    